-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

-- GRANT PRIVILEGES FOR THE TESTING USER TO ACCESS THE DB
GRANT ALL PRIVILEGES ON ecommerce_db.* TO 'test'@'localhost'; 